pipeline {
  agent {
    kubernetes {
      yamlFile 'kaniko-agent.yaml'
    }
  }

  environment {
    AWS_REGION = 'eu-north-1'
    ECR_REPO   = 'lesson-5-ecr'
    IMAGE_TAG  = "v${BUILD_NUMBER}"
    IMAGE_NAME = "${ECR_REPO}:${IMAGE_TAG}"
    ECR_URL    = "348962334695.dkr.ecr.eu-north-1.amazonaws.com"
  }

  stages {
    stage('Clone App') {
      steps {
        git url: 'https://github.com/renerroll/django-app.git', branch: 'main'
      }
    }

    stage('Build & Push to ECR') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context `pwd` \
              --dockerfile Dockerfile \
              --destination $ECR_URL/$IMAGE_NAME
          '''
        }
      }
    }

    stage('Update Helm Chart') {
      steps {
        git url: 'https://github.com/renerroll/django-helm.git', branch: 'main', changelog: false, poll: false
        dir('django-helm') {
          script {
            def values = readYaml file: 'values.yaml'
            values.image.tag = "${IMAGE_TAG}"
            writeYaml file: 'values.yaml', data: values
          }
          sh '''
            git config user.name "Jenkins Bot"
            git config user.email "jenkins@example.com"
            git add values.yaml
            git commit -m "Update image tag to $IMAGE_TAG"
            git push origin main
          '''
        }
      }
    }
  }
}
