image:
  repository: 348962334695.dkr.ecr.eu-north-1.amazonaws.com/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaler:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuThreshold: 70

env:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
